import AndExpression from './../lib/expressions/andExpression';
import OrExpression from './../lib/expressions/orExpression';
import ExistsExpression from './../lib/expressions/existsExpression';
import ContextExpression from './../lib/expressions/contextExpression';
import ImpliesExpression from './../lib/expressions/impliesExpression';
import InvariantExpression from './../lib/expressions/invariantExpression';
import IsEmptyExpression from './../lib/expressions/isEmptyExpression';
import IsNotEmptyExpression from './../lib/expressions/isNotEmptyExpression';
import IteratorExpression from './../lib/expressions/iteratorExpression';
import LetExpression from './../lib/expressions/letExpression';
import NumberExpression from './../lib/expressions/numberExpression';
import OperationCallExpression from './../lib/expressions/operationCallExpression';
import StringExpression from './../lib/expressions/stringExpression';
import BooleanExpression from './../lib/expressions/booleanExpression';
import VariableExpression from './../lib/expressions/variableExpression';
import NilExpression from './../lib/expressions/nilExpression';
import SizeExpression from './../lib/expressions/sizeExpression';
import {UnionOperation, AtOperation, FirstOperation, LastOperation, AsSetOperation} from './../lib/expressions/sequenceExpressions';
import SelectExpression from './../lib/expressions/selectExpression';

/* parser generated by jison 0.4.17 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var parser = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,7],$V1=[1,11],$V2=[1,12],$V3=[1,9],$V4=[5,11,15,18,19,20,22,23,24,25,26,27,28,29,30,31,33,34,40,41,50],$V5=[2,45],$V6=[5,11,15],$V7=[2,38],$V8=[1,16],$V9=[1,22],$Va=[1,25],$Vb=[1,26],$Vc=[1,27],$Vd=[1,28],$Ve=[1,29],$Vf=[1,30],$Vg=[1,45],$Vh=[1,34],$Vi=[1,35],$Vj=[1,36],$Vk=[1,37],$Vl=[1,38],$Vm=[1,39],$Vn=[1,40],$Vo=[1,41],$Vp=[1,42],$Vq=[1,43],$Vr=[1,44],$Vs=[1,46],$Vt=[5,11,15,18,19,20,22,23,24,25,26,27,28,29,30,31,34],$Vu=[2,35],$Vv=[1,48],$Vw=[5,11,15,19,28,29,30,34],$Vx=[33,40],$Vy=[1,78],$Vz=[2,33];
var parser = {trace: function trace() { },
yy: {},
symbols_: {"error":2,"contextDeclList":3,"contextDeclaration":4,"EOF":5,"classifierContextDecl":6,"context":7,"pathName":8,"invOrDefList":9,"invOrDef":10,"inv":11,"simpleNameOptional":12,":":13,"oclExpression":14,"def":15,"defExpression":16,"preOptional":17,"(":18,")":19,".":20,"simpleName":21,"<":22,"<=":23,"=":24,">=":25,">":26,"<>":27,"and":28,"or":29,"xor":30,"->":31,"variableDeclarationList":32,"|":33,"implies":34,"literalExp":35,"let":36,"type":37,"variableDeclaration":38,"typeOptional":39,",":40,"@":41,"pre":42,"primitiveLiteralExp":43,"integer":44,"real":45,"string":46,"true":47,"false":48,"nil":49,"::":50,"$accept":0,"$end":1},
terminals_: {2:"error",5:"EOF",7:"context",11:"inv",13:":",15:"def",18:"(",19:")",20:".",21:"simpleName",22:"<",23:"<=",24:"=",25:">=",26:">",27:"<>",28:"and",29:"or",30:"xor",31:"->",33:"|",34:"implies",36:"let",40:",",41:"@",42:"pre",44:"integer",45:"real",46:"string",47:"true",48:"false",49:"nil",50:"::"},
productions_: [0,[3,2],[4,1],[6,3],[9,2],[9,1],[10,4],[10,4],[14,2],[14,3],[14,4],[14,3],[14,3],[14,3],[14,3],[14,3],[14,3],[14,3],[14,3],[14,3],[14,3],[14,6],[14,4],[14,3],[14,3],[14,1],[16,4],[16,3],[37,1],[38,2],[32,3],[32,1],[39,2],[39,0],[17,2],[17,0],[35,1],[12,1],[12,0],[43,1],[43,1],[43,1],[43,1],[43,1],[43,1],[8,1],[8,3]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:
 return $$[$0-1] 
break;
case 2: case 25: case 28: case 32: case 36: case 37: case 45:
 this.$ = $$[$0] 
break;
case 3:
 this.$ = new ContextExpression($$[$0-1], $$[$0]) 
break;
case 4:
 this.$ = $$[$0-1].concat($$[$0]) 
break;
case 5: case 31:
 this.$ = [$$[$0]] 
break;
case 6:
 this.$ = new InvariantExpression($$[$0], $$[$0-2]) 
break;
case 7: case 26: case 27:
 this.$ = new LetExpression($$[$0-2], $$[$0]) 
break;
case 8:
 this.$ = new VariableExpression($$[$0-1]) 
break;
case 9: case 29:
 this.$ = $$[$0-1] 
break;
case 10:
 this.$ = ($$[$0-3] instanceof VariableExpression) ? new VariableExpression([$$[$0-3].variable, $$[$0-1]].join('.')) : $$[$0-3] 
break;
case 11:
 this.$ = new OperationCallExpression('<', $$[$0-2], $$[$0]) 
break;
case 12:
 this.$ = new OperationCallExpression('<=', $$[$0-2], $$[$0]) 
break;
case 13:
 this.$ = new OperationCallExpression('=', $$[$0-2], $$[$0]) 
break;
case 14:
 this.$ = new OperationCallExpression('>=', $$[$0-2], $$[$0]) 
break;
case 15:
 this.$ = new OperationCallExpression('>', $$[$0-2], $$[$0]) 
break;
case 16:
 this.$ = new OperationCallExpression('<>', $$[$0-2], $$[$0]) 
break;
case 17:
 this.$ = new AndExpression($$[$0-2], $$[$0]) 
break;
case 18:
 this.$ = new OrExpression($$[$0-2], $$[$0]) 
break;
case 19:
 this.$ = new XorExpression($$[$0-2], $$[$0]) 
break;
case 20:
 this.$ = functionCallExpression($$[$0], this.$); 
break;
case 21:
 $$[$0-5].body = $$[$0-1]; $$[$0-5].iterators = $$[$0-3]; this.$ = $$[$0-5] 
break;
case 22:
 $$[$0-3].body = $$[$0-1]; this.$ = $$[$0-3] 
break;
case 23:
  
break;
case 24:
 this.$ = new ImpliesExpression($$[$0-2], $$[$0]) 
break;
case 30:
 this.$ = [].concat($$[$0-2]).concat($$[$0]) 
break;
case 39: case 40:
 this.$ = new NumberExpression($$[$0]) 
break;
case 41:
 this.$ = new StringExpression($$[$0]) 
break;
case 42:
 this.$ = new BooleanExpression(true) 
break;
case 43:
 this.$ = new BooleanExpression(false) 
break;
case 44:
 this.$ = new NilExpression() 
break;
case 46:
 this.$ = $$[$0-2] 
break;
}
},
table: [{3:1,4:2,6:3,7:[1,4]},{1:[3]},{5:[1,5]},{5:[2,2]},{8:6,21:$V0},{1:[2,1]},{9:8,10:10,11:$V1,15:$V2,50:$V3},o($V4,$V5),{5:[2,3],10:13,11:$V1,15:$V2},{21:[1,14]},o($V6,[2,5]),{12:15,13:$V7,21:$V8},{12:17,13:$V7,21:$V8},o($V6,[2,4]),o($V4,[2,46]),{13:[1,18]},{13:[2,37]},{13:[1,19]},{8:21,14:20,18:$V9,21:$V0,35:23,43:24,44:$Va,45:$Vb,46:$Vc,47:$Vd,48:$Ve,49:$Vf},{16:31,21:[1,33],36:[1,32]},o($V6,[2,6],{18:$Vg,20:$Vh,22:$Vi,23:$Vj,24:$Vk,25:$Vl,26:$Vm,27:$Vn,28:$Vo,29:$Vp,30:$Vq,31:$Vr,34:$Vs}),o($Vt,$Vu,{17:47,41:$Vv,50:$V3}),{8:21,14:49,18:$V9,21:$V0,35:23,43:24,44:$Va,45:$Vb,46:$Vc,47:$Vd,48:$Ve,49:$Vf},o($Vt,[2,25]),o($Vt,[2,36]),o($Vt,[2,39]),o($Vt,[2,40]),o($Vt,[2,41]),o($Vt,[2,42]),o($Vt,[2,43]),o($Vt,[2,44]),o($V6,[2,7]),{21:[1,50]},{13:[1,51]},{21:[1,52]},{8:21,14:53,18:$V9,21:$V0,35:23,43:24,44:$Va,45:$Vb,46:$Vc,47:$Vd,48:$Ve,49:$Vf},{8:21,14:54,18:$V9,21:$V0,35:23,43:24,44:$Va,45:$Vb,46:$Vc,47:$Vd,48:$Ve,49:$Vf},{8:21,14:55,18:$V9,21:$V0,35:23,43:24,44:$Va,45:$Vb,46:$Vc,47:$Vd,48:$Ve,49:$Vf},{8:21,14:56,18:$V9,21:$V0,35:23,43:24,44:$Va,45:$Vb,46:$Vc,47:$Vd,48:$Ve,49:$Vf},{8:21,14:57,18:$V9,21:$V0,35:23,43:24,44:$Va,45:$Vb,46:$Vc,47:$Vd,48:$Ve,49:$Vf},{8:21,14:58,18:$V9,21:$V0,35:23,43:24,44:$Va,45:$Vb,46:$Vc,47:$Vd,48:$Ve,49:$Vf},{8:21,14:59,18:$V9,21:$V0,35:23,43:24,44:$Va,45:$Vb,46:$Vc,47:$Vd,48:$Ve,49:$Vf},{8:21,14:60,18:$V9,21:$V0,35:23,43:24,44:$Va,45:$Vb,46:$Vc,47:$Vd,48:$Ve,49:$Vf},{8:21,14:61,18:$V9,21:$V0,35:23,43:24,44:$Va,45:$Vb,46:$Vc,47:$Vd,48:$Ve,49:$Vf},{21:[1,62]},{8:21,14:64,18:$V9,19:[1,65],21:[1,67],32:63,35:23,38:66,43:24,44:$Va,45:$Vb,46:$Vc,47:$Vd,48:$Ve,49:$Vf},{8:21,14:68,18:$V9,21:$V0,35:23,43:24,44:$Va,45:$Vb,46:$Vc,47:$Vd,48:$Ve,49:$Vf},o($Vt,[2,8]),{42:[1,69]},{18:$Vg,19:[1,70],20:$Vh,22:$Vi,23:$Vj,24:$Vk,25:$Vl,26:$Vm,27:$Vn,28:$Vo,29:$Vp,30:$Vq,31:$Vr,34:$Vs},{13:[1,71]},{8:21,14:72,18:$V9,21:$V0,35:23,43:24,44:$Va,45:$Vb,46:$Vc,47:$Vd,48:$Ve,49:$Vf},o($Vt,$Vu,{17:73,41:$Vv}),o($Vw,[2,11],{18:$Vg,20:$Vh,22:$Vi,23:$Vj,24:$Vk,25:$Vl,26:$Vm,27:$Vn,31:$Vr}),o($Vw,[2,12],{18:$Vg,20:$Vh,22:$Vi,23:$Vj,24:$Vk,25:$Vl,26:$Vm,27:$Vn,31:$Vr}),o($Vw,[2,13],{18:$Vg,20:$Vh,22:$Vi,23:$Vj,24:$Vk,25:$Vl,26:$Vm,27:$Vn,31:$Vr}),o($Vw,[2,14],{18:$Vg,20:$Vh,22:$Vi,23:$Vj,24:$Vk,25:$Vl,26:$Vm,27:$Vn,31:$Vr}),o($Vw,[2,15],{18:$Vg,20:$Vh,22:$Vi,23:$Vj,24:$Vk,25:$Vl,26:$Vm,27:$Vn,31:$Vr}),o($Vw,[2,16],{18:$Vg,20:$Vh,22:$Vi,23:$Vj,24:$Vk,25:$Vl,26:$Vm,27:$Vn,31:$Vr}),o($Vw,[2,17],{18:$Vg,20:$Vh,22:$Vi,23:$Vj,24:$Vk,25:$Vl,26:$Vm,27:$Vn,31:$Vr}),o($Vw,[2,18],{18:$Vg,20:$Vh,22:$Vi,23:$Vj,24:$Vk,25:$Vl,26:$Vm,27:$Vn,31:$Vr}),o($Vw,[2,19],{18:$Vg,20:$Vh,22:$Vi,23:$Vj,24:$Vk,25:$Vl,26:$Vm,27:$Vn,31:$Vr}),o($Vt,[2,20]),{33:[1,74],40:[1,75]},{18:$Vg,19:[1,76],20:$Vh,22:$Vi,23:$Vj,24:$Vk,25:$Vl,26:$Vm,27:$Vn,28:$Vo,29:$Vp,30:$Vq,31:$Vr,34:$Vs},o($Vt,[2,23]),o($Vx,[2,31]),o([18,19,20,22,23,24,25,26,27,28,29,30,31,34,41,50],$V5,{39:77,13:$Vy,33:$Vz,40:$Vz}),o($Vw,[2,24],{18:$Vg,20:$Vh,22:$Vi,23:$Vj,24:$Vk,25:$Vl,26:$Vm,27:$Vn,31:$Vr}),o($Vt,[2,34]),o($Vt,[2,9]),{8:21,14:79,18:$V9,21:$V0,35:23,43:24,44:$Va,45:$Vb,46:$Vc,47:$Vd,48:$Ve,49:$Vf},o($V6,[2,27],{18:$Vg,20:$Vh,22:$Vi,23:$Vj,24:$Vk,25:$Vl,26:$Vm,27:$Vn,28:$Vo,29:$Vp,30:$Vq,31:$Vr,34:$Vs}),o($Vt,[2,10]),{8:21,14:80,18:$V9,21:$V0,35:23,43:24,44:$Va,45:$Vb,46:$Vc,47:$Vd,48:$Ve,49:$Vf},{21:[1,82],38:81},o($Vt,[2,22]),o($Vx,[2,29]),{8:84,21:$V0,37:83},o($V6,[2,26],{18:$Vg,20:$Vh,22:$Vi,23:$Vj,24:$Vk,25:$Vl,26:$Vm,27:$Vn,28:$Vo,29:$Vp,30:$Vq,31:$Vr,34:$Vs}),{18:$Vg,19:[1,85],20:$Vh,22:$Vi,23:$Vj,24:$Vk,25:$Vl,26:$Vm,27:$Vn,28:$Vo,29:$Vp,30:$Vq,31:$Vr,34:$Vs},o($Vx,[2,30]),o($Vx,$Vz,{39:77,13:$Vy}),o($Vx,[2,32]),o($Vx,[2,28],{50:$V3}),o($Vt,[2,21])],
defaultActions: {3:[2,2],5:[2,1],16:[2,37]},
parseError: function parseError(str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        function _parseError (msg, hash) {
            this.message = msg;
            this.hash = hash;
        }
        _parseError.prototype = Error;

        throw new _parseError(str, hash);
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};


function functionCallExpression(fn, source) {
    if(fn.toLowerCase() === 'isempty') {
        return new IsEmptyExpression(source);
    } else if(fn.toLowerCase() === 'isnotempty') {
        return new IsNotEmptyExpression(source);
    } else if(fn.toLowerCase() === 'size') {
        return new SizeExpression(source);
    } else if(fn.toLowerCase() === 'forall') {
        return new IteratorExpression(source);
    } else if(fn.toLowerCase() === 'select') {
        return new SelectExpression(source);
    } else if(fn.toLowerCase() === 'exists') {
        return new ExistsExpression(source);
    } else if(fn.toLowerCase() === 'union') {
       return new UnionOperation(source);
   } else if(fn.toLowerCase() === 'first') {
       return new FirstOperation(source);
   } else if(fn.toLowerCase() === 'at') {
       return new AOperation(source);
   } else if(fn.toLowerCase() === 'last') {
       return new LastOperation(source);
   } else if(fn.toLowerCase() === 'asset') {
       return new AsSetOperation(source);
   }

    throw new Error(`No function call expression found for '${fn}' not found!`);
}

function simplePropertyCall(operationName, optionalPre, optionalQualifiers, optionalPropertyCallParams) {
    const operations = ['<','<=','=', '=>', '>', '<>'];
    if(operations.indexOf(operationName) !== -1) {
    } else {
        return new VariableExpression(operationName);
    }
}
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function (match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex() {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin(condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState() {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules() {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState(n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState(condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:/* ignore */
break;
case 1:return 7
break;
case 2:return 11
break;
case 3:return 15
break;
case 4:return 36
break;
case 5:return 47
break;
case 6:return 48
break;
case 7:return 28
break;
case 8:return 29
break;
case 9:return 30
break;
case 10:return 34
break;
case 11:return 18
break;
case 12:return 19
break;
case 13:return 33
break;
case 14:return 31
break;
case 15:return 23
break;
case 16:return 25
break;
case 17:return 27
break;
case 18:return 22
break;
case 19:return 24
break;
case 20:return 26
break;
case 21:return 50
break;
case 22:return 13
break;
case 23:return 20
break;
case 24:return 40
break;
case 25:return 41
break;
case 26:return 42
break;
case 27:return 49
break;
case 28:return 21
break;
case 29:return 46
break;
case 30:return 44
break;
case 31:return 45
break;
case 32:return 5
break;
case 33:return 'ERROR'
break;
}
},
rules: [/^(?:\s+)/,/^(?:context\b)/,/^(?:inv\b)/,/^(?:def\b)/,/^(?:let\b)/,/^(?:true\b)/,/^(?:false\b)/,/^(?:and\b)/,/^(?:or\b)/,/^(?:xor\b)/,/^(?:implies\b)/,/^(?:\()/,/^(?:\))/,/^(?:\|)/,/^(?:->)/,/^(?:<=)/,/^(?:>=)/,/^(?:<>)/,/^(?:<)/,/^(?:=)/,/^(?:>)/,/^(?:::)/,/^(?::)/,/^(?:\.)/,/^(?:,)/,/^(?:@)/,/^(?:pre\b)/,/^(?:nil\b)/,/^(?:[a-zA-Z][a-zA-Z0-9]*)/,/^(?:["][^\"]*["])/,/^(?:[0-9][0-9]*)/,/^(?:[0-9][0-9]+\.[0-9]*)/,/^(?:$)/,/^(?:.)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = parser;
exports.Parser = parser.Parser;
exports.parse = function () { return parser.parse.apply(parser, arguments); };
exports.main = function commonjsMain(args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}