name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Run tests
        run: |
          npm ci
          npm test

  tag:
    needs: build
    name: Release on GH
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Run build
        run: |
          npm ci
          npm run build
          npm run build:examples
        env:
          RUN_SLOW_TESTS: true
      - name: Extract version
        run: |
          echo "::set-env name=PACKAGE_VERSION::$(grep -m1 version package.json | awk -F: '{ print $2 }' | sed 's/[", ]//g')"
      - name: Create a GH release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.PACKAGE_VERSION }}
          release_name: v${{ env.PACKAGE_VERSION }}
